### PR TITLE
Add dependencies

### PR DESCRIPTION
**Pull request by ghost**
ping @Hainish.
This will speed up Travis builds and make requirements.txt files and https-everywhere Dockerfile unneeded.

### CODE REVIEW

**Comment by ghost** [comment]
@Hainish We also need to check which packages are still used.

**Comment by Hainish** [comment]
I intentionally separated this out.  Since downloading is faster than building, it's better to download the base image *in most cases*.

But it makes sense to keep the python dependencies for HTTPS Everywhere in the main repo.  If these dependencies change for any given PR, we want to make sure that the build still works.  This base docker image doesn't change very often, so building the python dependencies from the actual `requirements.txt` file in any given PR makes the most sense.

**Comment by ghost** [comment]
@Hainish `ENV FIREFOX firefox-latest/firefox/firefox` probably still belongs here.

**Comment by ghost** [comment]
@Hainish Likely the same with `WORKDIR /opt`

**Comment by ghost** [comment]
@Hainish This requirement list is a merge and de-duplication of the two `requirements.txt` files installed by HTTPS Everywhere Dockerfile.

**Comment by ghost** [comment]
@Hainish Installing Python dependencies each time pointlessly delays each Travis run, no matter if it's going to use them or not, they are always installed each time.

**Pull request closed without merging**
